version: "2"
services:
  mc1:
    build: .
    command: java -jar /app/mc1/target/mc1-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/springbootdb
    ports:
      - "8082:8082"
  mc2:
    build: .
    command: java -jar /app/mc2/target/mc2-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/springbootdb
    ports:
      - "8083:8083"

