version: "2"
services:
  circlemessaging:
    build: .
    command: java -jar /mc1/target/mc1-0.0.1-SNAPSHOT.war && java -jar /mc2/target/mc1-0.0.1-SNAPSHOT.war
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/springbootdb
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - circlemessaging

networks:
  circlemessaging: null