interaction:
  interval-ms: '1000'
server:
  port: '8082'
spring:
  datasource:
    url: 'jdbc:mariadb://mariadb:3306/springbootdb'
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
